import type { Metadata } from "next";

import "@/app/globals.css"
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import { ApolloProvider } from "@apollo/client";
import client from "@/lib/apolloClient";
import CustomApolloProvider from "@/lib/apollo-provider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <CustomApolloProvider>
          <div className="container">
          {children}
          </div>
        
        </CustomApolloProvider>
        
        </body>
    </html>
  );
}
